# Generated by Django 5.0.6 on 2024-05-31 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_image', models.ImageField(default='default_user.png', help_text='أختر صورة رمزية تمثلك', null=True, upload_to='prof_images/%Y/%m/%d/', verbose_name='صورة شخصية')),
                ('prof_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ إنشاء الملف الشخصي')),
                ('prof_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ آخر تحديث للملف الشخصي')),
                ('prof_mob', models.CharField(help_text='ضع رقم الجوال بالصيغة الدولية مثلا (جوال سعودي 00966501234567)', max_length=14, null=True, unique=True, verbose_name='رقم الجوال')),
                ('gender', models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=10, null=True, verbose_name='الجنس')),
                ('user_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
