# Generated by Django 5.0.6 on 2024-05-31 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ إنشاء الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(default='default_user.png', help_text='أختر صورة رمزية تمثلك', null=True, upload_to='prof_images/%Y/%m/%d/', verbose_name='صورة شخصية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof_mob',
            field=models.CharField(help_text='ضع رقم الجوال بالصيغة الدولية مثلا (جوال سعودي 00966501234567)', max_length=14, null=True, unique=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ آخر تحديث للملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
