# Generated by Django 5.0.6 on 2024-05-31 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_created',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments_to_author', to=settings.AUTH_USER_MODEL, verbose_name='كاتب التعليق'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ النشر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(help_text='يجب أن لا يتجاوز طول النص 4000', max_length=4000, null=True, verbose_name='نص التعليق'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_post', to='blog_app.post', verbose_name='تابع للموضوع'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_to_author', to=settings.AUTH_USER_MODEL, verbose_name='Post author'),
        ),
    ]
